# fly.toml file generated for wild-night-9961 on 2023-04-03T06:12:13-05:00

app = "wild-night-9961"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bog"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
