spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
stripe:
  api:
    base:
      url: https://api.stripe.com
  key:
    public: pk_test_51MWqRxIxcd7KGrT5cpoAacalzkt4yKbxIPLNxfyfffbS7lOxGTCDiGVXzohUFRDdWEs1lH8AMY72Fg63Z6lM5P6K00QiKODldT
    secret: sk_test_51MWqRxIxcd7KGrT5brAhFhGuWOkRJWW5qFhGKxZtNbrzaZjau19jlg2kjWWDvqi0ucSmfBes360GszSPh33uCdRR00rTfMNOb2
